### ISSUE TITLE
Naming of gem

### ISSUE THREAD

**Issue by ksss** [blocknotes/rubocop-rbs#4]
@blocknotes 

Hi 👋  I'm ksss.
Thanks for the nice gem. It is a great inspiration.

I have been working on the development of the RBS ecosystem for several years. This time, I was preparing an extension gem for RuboCop as a linting system for RBS files.
This tool aims to provide suggestions and auto-corrections for issues such as indentation and replacing `(true | false)` with `bool`, operating seamlessly within the RuboCop ecosystem.

The first name that came to mind for this tool was `rubocop-rbs` (Yes, This is it).
I am concerned that naming my tool something like `rubocop-rbs-sig`. However, I might cause confusion in the community.

Here are the options I am considering:

- Simply release `rubocop-rbs-sig`.
- Merge `rubocop-rbs` and `rubocop-rbs-sig`.
- Change the name of `rubocop-rbs`.

I would greatly appreciate your thoughts on this matter.

**Comment by ksss** [comment]
@blocknotes 
I would appreciate hearing your thoughts at this stage.

**Comment by blocknotes** [comment]
Hi @ksss 

> I have been working on the development of the RBS ecosystem for several years. This time, I was preparing an extension gem for RuboCop as a linting system for RBS files. This tool aims to provide suggestions and auto-corrections for issues such as indentation and replacing `(true | false)` with `bool`, operating seamlessly within the RuboCop ecosystem.

Nice, this is partially the same purpose of my gem.

> Here are the options I am considering:
>     * Simply release `rubocop-rbs-sig`.

This is of course a choice on your side, so it's up to you.

>     * Merge `rubocop-rbs` and `rubocop-rbs-sig`.

What do you mean exactly with "merging" 2 different projects? 🤔 

If you are still evaluating this option a common way that I would expect is proposing pull requests to this project.

>     * Change the name of `rubocop-rbs`.

This is not feasible because it would be a gem hijacking => the people who are already using this component would expect to download the same project (not a completely different one) when referring to _rubocop-rbs_ gem (for example when an update is released).

> I would greatly appreciate your thoughts on this matter.

Setting a gem name is like choosing a domain or a username of a service, if it's already taken I would simply suggest to use a different one 🤷

**Comment by ksss** [comment]
Thanks for the reply.
I have already chosen to release it under a different name.
Someone in my community suggested that I ask if you could give up the name "rubocop-rbs." I decided to reach out based on that suggestion. Since I didn't receive a response for three weeks, I had given up on this option.
Thanks.
